name: automate image push to dockerhub

# on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        Password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and publish
      run: |
        registry="paramtoora"
        sha=$(git rev-parse --short HEAD)
        primary_tag="${registry}/cicd-test:${sha}"

        docker build -t "$primary_tag" -f CICD/Dockerfile CICD
        docker push $primary_tag
